name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Clippy
      run: rustup component add clippy && cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
